### ISSUE TITLE
Ambiguous overloaded call to 'StrNew'   System.SysUtils.pas(12011)

### ISSUE THREAD

**Issue by ms301** [ahausladen/DLangExtensions#1]
RAD = Seattle
Source = Last comit
Error
`[dcc32 Error] Utf8StringUtils.pas(452): E2251 Ambiguous overloaded call to 'StrNew'
  System.SysUtils.pas(12011): Related method: function StrNew(const PAnsiChar): PAnsiChar;
  System.AnsiStrings.pas(3921): Related method: function StrNew(const PAnsiChar): PAnsiChar;`

**Comment by ahausladen** [comment]
Delphi 2009 is the last version that was supported. There is no further development.
